/**
 * Created by tfakioglu on 12.December.2021
 */

object Versions {
    const val inject = "1"
    const val gradle = "7.0.4"
    const val compilerExtension = "1.1.0-beta04"
    const val coroutines = "1.6.4"
    const val hilt = "2.44"
    const val material = "1.6.0"
    const val core = "1.9.0"
    const val appcompat = "1.4.1"
    const val compose = "1.3.2"
    const val composeMaterial = "1.3.1"
    const val materialIconExtended = "1.4.0-alpha03"
    const val materialIconCore = "1.3.1"
    const val activityCompose = "1.6.1"
    const val navigationCompose = "2.6.0-alpha04"
    const val hiltNavigationCompose = "1.1.0-alpha01"
    const val lifecycle = "2.5.1"
    const val lifecycleCompose = "2.5.1"
    const val pagingCompose = "1.0.0-alpha17"
    const val room = "2.3.0"
    const val retrofit = "2.9.0"
    const val okhttpLogging = "4.9.3"
    const val coil = "2.2.1"
    const val junitExt = "1.1.4"
    const val espresso = "3.5.0"
    const val junit = "4.13.2"
    const val lottieCompose = "4.2.2"
    const val sweetToast = "1.0.1"
    const val swipeRefresh = "0.21.0-beta"
    const val kotlinGradle = "1.6.0"
}